const fs = require("fs");
const path = require("path");

const rootDir = __dirname;
const outputFile = path.join(rootDir, "frontend-config.js");
const envFiles = [
  path.join(rootDir, ".env"),
  path.join(rootDir, ".env.production")
];

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, "utf8");
  const result = {};

  raw.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) return;
    const idx = trimmed.indexOf("=");
    if (idx <= 0) return;
    const key = trimmed.slice(0, idx).trim();
    let value = trimmed.slice(idx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[key] = value;
  });

  return result;
}

const merged = {};
for (const filePath of envFiles) {
  Object.assign(merged, parseEnvFile(filePath));
}
Object.assign(merged, process.env);

const converterApiBase = String(
  merged.FRONTEND_CONVERTER_API_BASE ||
  merged.CONVERTER_API_BASE ||
  merged.NEXT_PUBLIC_CONVERTER_API_BASE ||
  merged.VITE_CONVERTER_API_BASE ||
  ""
).trim().replace(/\/+$/, "");

const fileContent = `// Generated by build-config.js
// Do not edit this file directly if you are deploying with Vercel env/build flow.
window.CONVERTER_API_BASE = window.CONVERTER_API_BASE || ${JSON.stringify(converterApiBase)};
`;

fs.writeFileSync(outputFile, fileContent, "utf8");
console.log(`Generated frontend-config.js with CONVERTER_API_BASE=${converterApiBase || "(empty)"}`);
