// Generated by build-config.js
// Do not edit this file directly if you are deploying with Vercel env/build flow.
window.CONVERTER_API_BASE = window.CONVERTER_API_BASE || "https://makepdf-backend.onrender.com";
window.ALLOW_BROWSER_DOCX_PDF_FALLBACK = "0";
